# Generated by Django 5.2.4 on 2025-07-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('ciclo', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
